### ISSUE TITLE
My Discord 

### ISSUE THREAD

**Issue by FreezeFlameKill** [iBLiSSIN/SurvivMods#2]
Want to 1v1 some time? We can set up a 1v1 on discord. Give me your discord, I forgot mine lol

**Comment by iBLiSSIN** [comment]
Hi

**Comment by iBLiSSIN** [comment]
https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqblRJVzR1T2l0LVdUYWJRUUJtX08xSUFIMnFpQXxBQ3Jtc0tuVzVDMEEyMFlObE1SREIzcV9iTlRlcGVSemtuRjdsY19IX2RnMVRaR0VEXzNabzFqV05NZWY3U1VCeVE2V3VtSXBnMVEzMEVCcFhOSlVxUXFLY250eXAxV3VjMVNlRS1TcnFoMkZuNEE0b0hGWnppYw&q=https%3A%2F%2Fdiscord.gg%2FzrtxKHS7&stzid=Ugx2wKhThLHD8lJ7E3F4AaABAg.9NsrxTszUXa9NtDNjRgw2D

**Comment by iBLiSSIN** [comment]
https://discord.com/invite/zrtxKHS7

**Comment by iBLiSSIN** [comment]
I am not iblissin, I’m a fan of him lol
